language: scala

scala:
  - 2.10.4
  - 2.11.5

jdk:
  - oraclejdk7
  - oraclejdk8

addons:
  postgresql: "9.3"

sudo: false

before_script:
  - rm project/sbt-idea.sbt
  - rm project/sbt-pgp.sbt
  - rm project/sbt-updates.sbt
  - psql -c "CREATE ROLE sa WITH SUPERUSER LOGIN PASSWORD 'sa';" -U postgres
  - psql -c "CREATE DATABASE scalikejdbc;" -U postgres
  - mysql -e 'GRANT ALL ON *.* TO sa@"localhost"IDENTIFIED BY "sa";FLUSH PRIVILEGES;' -uroot
  - mysql -e "CREATE DATABASE scalikejdbc;" -usa -psa

script:
  - ./travis.sh

env:
  matrix:
    - SCALIKEJDBC_DATABASE="mysql"
    - SCALIKEJDBC_DATABASE="postgresql"

matrix:
  include:
    - scala: scripted-test
      jdk: oraclejdk8
      env: SCALIKEJDBC_DATABASE="mysql"
    - scala: scripted-test
      jdk: oraclejdk8
      env: SCALIKEJDBC_DATABASE="postgresql"
    - scala: scripted-test
      jdk: oraclejdk8
      env: SCALIKEJDBC_DATABASE="h2"
    - scala: 2.11.5
      jdk: oraclejdk7
      env: SCALIKEJDBC_DATABASE="h2"
    - scala: 2.11.5
      jdk: oraclejdk7
      env: SCALIKEJDBC_DATABASE="hsqldb"
