language: scala

dist: xenial

services:
  - mysql

scala:
  - 2.12.12
  - 2.13.3

# The project supports OpenJDK 8+ / Oracle JDK 8,9,10
jdk:
  - openjdk8

addons:
  postgresql: "9.4"

sudo: false

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/launchers
    - $HOME/.sbt/boot

before_script:
  - rm project/sbt-pgp.sbt
  - rm project/sbt-updates.sbt
  - psql -c "CREATE ROLE sa WITH SUPERUSER LOGIN PASSWORD 'sa';" -U postgres
  - psql -c "CREATE DATABASE scalikejdbc;" -U postgres
  - mysql -e 'GRANT ALL ON *.* TO sa@"localhost"IDENTIFIED BY "sa";FLUSH PRIVILEGES;' -uroot
  - mysql -e "CREATE DATABASE scalikejdbc;" -usa -psa
  - mysql -e "ALTER DATABASE scalikejdbc CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;" -usa -psa
  - bash -x ./travis_before.sh

script:
  - git add . --all
  - travis_retry ./travis.sh

before_cache:
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
  - find $HOME/.ivy2/cache -name "*SNAPSHOT*" | xargs rm -rf

env:
  matrix:
    - SCALIKEJDBC_DATABASE="mysql"
    - SCALIKEJDBC_DATABASE="postgresql"

matrix:
  include:
    - name: dotty
      script:
      - sbt '++ 0.27.0-RC1!' "all interpolation/test:compile joda-time/compile library/test mapper-generator-core/test streams/test config/test"
    # scripted test
    - scala: scripted-test
      env: SCALIKEJDBC_DATABASE="mysql"
    - scala: scripted-test
      env: SCALIKEJDBC_DATABASE="postgresql"
    - scala: scripted-test
      env: SCALIKEJDBC_DATABASE="h2"
    # h2, hsqldb
    - scala: 2.12.12
      env: SCALIKEJDBC_DATABASE="h2"
    - scala: 2.12.12
      env: SCALIKEJDBC_DATABASE="hsqldb"
    # Disabled because the sbt initialization with OpenJDK9/10 are somehow unstable
    #- scala: 2.12.12
    #  env: SCALIKEJDBC_DATABASE="mysql"
    #  jdk: openjdk9
    #- scala: 2.12.12
    #  env: SCALIKEJDBC_DATABASE="mysql"
    #  jdk: openjdk10
    - scala: 2.12.12
      env: SCALIKEJDBC_DATABASE="mysql"
      jdk: openjdk11
    - os: windows
      language: bash
      env: JDK="adopt@1.8.0-222"
      before_script:
      - curl "https://raw.githubusercontent.com/DanySK/Gravis-CI/c8f400623d8f756ef7c/.install-jdk-travis.sh" --output .install-jdk-travis.sh
      - source .install-jdk-travis.sh
      - wget https://raw.githubusercontent.com/paulp/sbt-extras/4d558c88ae6ae240e7a5eedc0cf33cc9e7bd0e58/sbt && chmod +x ./sbt
      script:
      - ./sbt "project root213" "++ 2.12.12" test:compile testSequential
