language: scala

scala:
  - 2.10.6
  - 2.11.7

jdk:
  - oraclejdk7
  - oraclejdk8

addons:
  postgresql: "9.4"

sudo: false

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot

before_script:
  - rm project/sbt-idea.sbt
  - rm project/sbt-pgp.sbt
  - rm project/sbt-updates.sbt
  - psql -c "CREATE ROLE sa WITH SUPERUSER LOGIN PASSWORD 'sa';" -U postgres
  - psql -c "CREATE DATABASE scalikejdbc;" -U postgres
  - mysql -e 'GRANT ALL ON *.* TO sa@"localhost"IDENTIFIED BY "sa";FLUSH PRIVILEGES;' -uroot
  - mysql -e "CREATE DATABASE scalikejdbc;" -usa -psa

script:
  - bash -x ./travis_before.sh
  - git add . --all
  - travis_retry ./travis.sh
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
  - find $HOME/.ivy2/cache -name "*SNAPSHOT*" | xargs rm -rf

env:
  matrix:
    - SCALIKEJDBC_DATABASE="mysql"
    - SCALIKEJDBC_DATABASE="postgresql"

matrix:
  include:
    - scala: 2.12.0-M3
      jdk: oraclejdk8
      env: SCALIKEJDBC_DATABASE="mysql"
    - scala: scripted-test
      jdk: oraclejdk8
      env: SCALIKEJDBC_DATABASE="mysql"
    - scala: scripted-test
      jdk: oraclejdk8
      env: SCALIKEJDBC_DATABASE="postgresql"
    - scala: scripted-test
      jdk: oraclejdk8
      env: SCALIKEJDBC_DATABASE="h2"
    - scala: 2.11.7
      jdk: oraclejdk7
      env: SCALIKEJDBC_DATABASE="h2"
    - scala: 2.11.7
      jdk: oraclejdk7
      env: SCALIKEJDBC_DATABASE="hsqldb"
