language: scala

scala:
  - 2.10.6
  - 2.11.11
  - 2.12.2

jdk:
  - oraclejdk8

addons:
  postgresql: "9.4"

sudo: false

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/launchers
    - $HOME/.sbt/boot

before_script:
  - rm project/sbt-pgp.sbt
  - rm project/sbt-updates.sbt
  - psql -c "CREATE ROLE sa WITH SUPERUSER LOGIN PASSWORD 'sa';" -U postgres
  - psql -c "CREATE DATABASE scalikejdbc;" -U postgres
  - mysql -e 'GRANT ALL ON *.* TO sa@"localhost"IDENTIFIED BY "sa";FLUSH PRIVILEGES;' -uroot
  - mysql -e "CREATE DATABASE scalikejdbc;" -usa -psa
  - mysql -e "ALTER DATABASE scalikejdbc CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;" -usa -psa

script:
  - bash -x ./travis_before.sh
  - git add . --all
  - travis_retry ./travis.sh
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
  - find $HOME/.ivy2/cache -name "*SNAPSHOT*" | xargs rm -rf

env:
  matrix:
    - SCALIKEJDBC_DATABASE="mysql"
    - SCALIKEJDBC_DATABASE="postgresql"

matrix:
  include:
    - scala: 2.12.2
      script:
      - echo "sbt.version=0.13.16-M1" > project/build.properties
      # TODO https://github.com/sbt/sbt/issues/3245 enable scripted test
      - sbt ++${TRAVIS_SCALA_VERSION} "project mapper-generator" "^^ 1.0.0-M6" compile
    - scala: scripted-test
      env: SCALIKEJDBC_DATABASE="mysql"
    - scala: scripted-test
      env: SCALIKEJDBC_DATABASE="postgresql"
    - scala: scripted-test
      env: SCALIKEJDBC_DATABASE="h2"
    - scala: 2.12.2
      env: SCALIKEJDBC_DATABASE="h2"
    - scala: 2.12.2
      env: SCALIKEJDBC_DATABASE="hsqldb"
    - scala: 2.13.0-M1
      env: SCALIKEJDBC_DATABASE="mysql"
      script:
      # https://github.com/scalikejdbc/scalikejdbc/issues/683
      - bash -x ./travis_before.sh
      - sbt ++${TRAVIS_SCALA_VERSION} config/test core/test interpolation/test interpolation-macro/test library/test syntax-support-macro/test mapper-generator-core/test
    - dist: trusty
      group: edge
      sudo: required
      scala: 2.12.2
      jdk: oraclejdk9
      env: SCALIKEJDBC_DATABASE="mysql"
      script:
      # https://github.com/sbt/sbt/pull/2951
      - git clone https://github.com/retronym/java9-rt-export
      - cd java9-rt-export/
      - git checkout 1019a2873d057dd7214f4135e84283695728395d
      - jdk_switcher use oraclejdk8
      - sbt package
      - jdk_switcher use oraclejdk9
      - mkdir -p $HOME/.sbt/0.13/java9-rt-ext; java -jar target/java9-rt-export-*.jar $HOME/.sbt/0.13/java9-rt-ext/rt.jar
      - jar tf $HOME/.sbt/0.13/java9-rt-ext/rt.jar | grep java/lang/Object
      - cd ..
      - echo "sbt.version=0.13.15" > project/build.properties
      - wget https://raw.githubusercontent.com/paulp/sbt-extras/9ade5fa54914ca8aded44105bf4b9a60966f3ccd/sbt && chmod +x ./sbt
      - bash -x ./travis_before.sh
      - ./sbt -Dscala.ext.dirs=$HOME/.sbt/0.13/java9-rt-ext ++$TRAVIS_SCALA_VERSION "project root211" test:compile testSequential
